AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'stats/test/**/*'
    - 'admin_panel/test/**/*'
    - 'Dangerfile'
    - 'dev/**.rb'
    - 'vendor/**.rb'
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
#  Enabled: false
Layout/FirstArgumentIndentation:
  IndentationWidth: 2
Layout/FirstHashElementIndentation:
  IndentationWidth: 2
Layout/MultilineMethodCallIndentation:
  IndentationWidth: 2
  EnforcedStyle: indented_relative_to_receiver
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  CountAsOne: ["array", "heredoc", "hash"]
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: true
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/EmptyElse:
  EnforcedStyle: empty
Style/FormatStringToken:
  EnforcedStyle: template
Style/IfUnlessModifier:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/NegatedIf:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
Metrics/LineLength:
  Max: 180
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'db/migrate/*'
Metrics/CyclomaticComplexity:
  Max: 7
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'
Metrics/ModuleLength:
  Max: 150
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  Max: 8
Metrics/AbcSize:
  Max: 17
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - draw
    - namespace
    - resources
    - it
    - configure
    - aasm
    - included
    - shared_examples_for
    - devise_scope
  Exclude:
    - 'db/migrate/*'
Style/Documentation:
  Enabled: false
