module Domains
  class RejectList
    REJECT_LIST = %w(
      aim.com
      alice.it
      aliceadsl.fr
      aol.com
      arcor.de
      att.net
      bellsouth.net
      bigpond.com
      bigpond.net.au
      blueyonder.co.uk
      bluewin.ch
      bol.com.br
      centurytel.net
      charter.net
      chello.nl
      club-internet.fr
      comcast.net
      cox.net
      earthlink.net
      facebook.com
      free.fr
      freenet.de
      frontiernet.net
      gmail.com
      gmx.de
      gmx.net
      googlemail.com
      hetnet.nl
      hey.com
      home.nl
      hotmail.com
      hotmail.co.uk
      hotmail.de
      hotmail.es
      hotmail.it
      hotmail.fr
      ig.com.br
      juno.com
      laposte.net
      libero.it
      live.ca
      live.co.uk
      live.com
      live.com.au
      live.fr
      live.it
      live.nl
      mac.com
      mail.com
      mail.ru
      me.com
      msn.com
      neuf.fr
      ntlworld.com
      optonline.net
      optusnet.com.au
      orange.fr
      outlook.com
      planet.nl
      qq.com
      rambler.ru
      rediffmail.com
      rocketmail.com
      sbcglobal.net
      shaw.ca
      sky.com
      skynet.be
      sfr.fr
      sympatico.ca
      tin.it
      tiscali.co.uk
      tiscali.it
      telenet.be
      terra.com.br
      t-online.de
      uol.com.br
      verizon.net
      virgilio.it
      voila.fr
      wanadoo.fr
      web.de
      windstream.net
      yahoo.ca
      yahoo.co.id
      yahoo.co.in
      yahoo.co.jp
      yahoo.co.uk
      yahoo.com
      yahoo.com.ar
      yahoo.com.au
      yahoo.com.br
      yahoo.com.sg
      yahoo.com.mx
      yahoo.de
      yahoo.es
      yahoo.fr
      yahoo.in
      yahoo.it
      yandex.ru
      ymail.com
      zonnet.nl
    )

    REJECT_LIST_INCLUDES =

    def self.include?(domain)
      REJECT_LIST.include?(domain.downcase.strip)
    end

    def self.cleaned_domain(domain)
      if self.include?(domain)
        nil
      else
        domain
      end
    end
  end
end
